# Generated by Django 4.1.1 on 2022-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('family_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Man'), ('Ж', 'Woman')], default='M', max_length=3)),
            ],
        ),
    ]
